### PR TITLE
remove disroot.org from your "manifest"

### PR DESCRIPTION
**Pull request by muppeth**
After smearing campaign, bullying and blackmailing into submission disroot.org does not want to have anything to do with this "manifest" nor it wants to be mentioned in it.

### CODE REVIEW

**Comment by E-404** [comment]
Do you consider the public coverage of your server’s security policy blackmail?
This is just a list of servers security policies. I think it is necessary to change the word manifest to another, because it scares some administrators.

**Comment by muppeth** [comment]
No I consider the way you were bullying into submission on our chat few weeks back, and insinuated something that isnt true, a blackmail. Also your snarky untrue and smearing tone of your previous comment does not show you or what your "manifest" tries to convey in the good light. We have had a user form your server this morning trying to insinuate things after they heard form your about disroot after they've spoken with you, where you spread lies about our project and the way we run things. We do not feel comfortable nor want to be affiliated with such behaviour and we'll not bend down to your manifest. 
Manifest that is not part of any offical recognized body within xmpp community, nor one that does any change or guarantees anything. 

By your actions within last week I'm more certain it is not about protecting users or server to server communication but satisfying your ego that seems like it wants to feel important. 

If I were to write a manifest that "Every XMPP server should run MUC module" and you wouldnt want o sign it, does it give me any authority to enforce it? Can I then start smearing campaign against you and your platform? Do I have any right to require you to sign it? No, I dont think so.

**Comment by muppeth** [comment]
> I think it is necessary to change the word manifest to another, because it scares some administrators.

No people are not interested in signing ton of documents that are meaningless. For instance I will fork you manifest and say "mine is the true one" and go on asking people to sing it. Easily we endup with multiple similar manifests about the same thing and we create more chaos chaos. You are in no authority to enforce such manifest and this is why we do secure s2s with valid certificate connections but we do not feel like there is a need for manifest that we need to sign with our name, no matter how you call it.

**Comment by muppeth** [comment]
And to be very clear about it. We do not in any shape or form Support your manifest so I think we should be listed in the other category (definatelly not after your recent actions). 

We do support the secure s2s connection, but as far as I'm aware you nor the manifest is not an author of the protocol nor s2s standards. **We support the standard we do not support your manifest!**

**Comment by E-404** [comment]
> No I consider the way you were bullying into submission on our chat few weeks back, and insinuated something that isnt true, a blackmail. 

You are mistaken if you think that you are blackmailing. We do not require you to use the manifest, it’s just an information sheet.

>We have had a user form your server this morning trying to insinuate things after they heard form your about disroot after they've spoken with you, where you spread lies about our project and the way we run things. 

Yes, we have to explain to users why they cannot connect to servers with untrusted certificates.
Yes, we have to tell users that other servers allow the use of self-signed certificates. This is a common user support job.

**Comment by E-404** [comment]
> And to be very clear about it. We do not in any shape or form Support your manifest so I think we should be listed in the other category (definatelly not after your recent actions).
> We do support the secure s2s connection, but as far as I'm aware you nor the manifest is not an author of the protocol nor s2s standards. **We support the standard we do not support your manifest!**


Let's take the word of the **manifesto**, replace the word **standard**, so as not to frighten you ?

**Comment by muppeth** [comment]
> Let's take the word of the manifesto, replace the word standard, so as not to frighten you ?
You still dont get the point. You are not the author nor you have authority to call that document a standard. I would just rename it to: *404.city checklist of who is using secure s2s*.

**Comment by E-404** [comment]
> You still dont get the point. You are not the author nor you have authority to call that document a standard. I would just rename it to: _404.city checklist of who is using secure s2s_.
This is not a personal 404.city list. It will be necessary to come up with a suitable name for the correct presentation of information.

**Comment by muppeth** [comment]
In the mean time please respect our wish to be removed from it.

**Comment by lunarthegrey** [comment]
How were you blackmailed @muppeth?

**Comment by E-404** [comment]
> How were you blackmailed @muppeth?
I said that it will be added to the list of not supporting the manifest. He thought it was blackmail.

**Comment by E-404** [comment]
@lunarthegrey
Express your opinion on whether to remove it from the list or not.

**Comment by lunarthegrey** [comment]
@E-404 I figure he should just be removed if he doesn't want to associate. As long as he forces valid certificates he shouldn't have an issue with other servers.

**Comment by E-404** [comment]
> @E-404 I figure he should just be removed if he doesn't want to associate. As long as he forces valid certificates he shouldn't have an issue with other servers.

I support your opinion. Decision is made.  @muppeth server will be deleted.  Perhaps it should be added to the list of only those who have invalid certificates, and not everyone?

**Comment by lunarthegrey** [comment]
> > @E-404 I figure he should just be removed if he doesn't want to associate. As long as he forces valid certificates he shouldn't have an issue with other servers.
> 
> I support your opinion. Decision is made. @muppeth server will be deleted. Perhaps it should be added to the list of only those who have invalid certificates, and not everyone?

Do they have invalid certificates? Sorry but I'm not completely aware of the situation. He made it seem like he supports the standard itself, but not the manifesto.

**Comment by E-404** [comment]
@lunarthegrey The meaning of this section is to explain to the users why they cannot connect to other servers. You expressed a simple and excellent idea, just to list servers with invalid certificates in the list of not supporting the manifest.This allows users to explain why they cannot connect in a simpler way.

If the server has invalid encryption and they have problems to add to the invalid encryption lis

**Comment by E-404** [comment]
To user question:
>Why can't I connect?

Server is blacklisted
>Why can I connect from another server?

The another server not on whitelist

**Pull request closed without merging**
